### ISSUE TITLE
Add ability to disable subscription-manager

### ISSUE THREAD

**Issue by bsper2** [ncsa/puppet-rhsm#2]
Would be nice to have the option to turn off subscription manager.

Ideally there is a command that can be run to enable/disable, but if not I edited the file `etc/yum/pluginconf.d/subscription-manager.conf` to change enabled status there.

This is useful for nodes like puppet/xcat server that are installed by hand and that also should normally have their repo urls pointing to the local xcat server or internal ncsa repo server. If subscription manager is on, then it will keep putting in place a redhat.repo file which clobbers repos you try to set in puppet.

**Comment by jakerundall** [comment]
Ben and I found that this command seems to fully disable RHSM management of repos (the redhat.repo file completely goes away in this case):
subscription-manager config --rhsm.manage_repos=0

Seems to update these files):
/etc/dnf/plugins/subscription-manager.conf
/etc/rhsm/rhsm.conf

**Comment by billglick** [comment]
As I worked on this, I did not see that the contents of the following file ever changed:
- `/etc/dnf/plugins/subscription-manager.conf`
