### ISSUE TITLE
When disabled. Proxy can't reference RHSM-register.

### ISSUE THREAD

**Issue by v1peractual** [ncsa/puppet-rhsm#4]
There needs to be a disable clause in the proxy.pp as the proxy is still referenced when disabled but private.

Error: Facter: Error while resolving custom fact fact='sssd_domains', resolution='<anonymous>': no implicit conversion of nil into String
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Could not find resource 'Exec[RHSM-register]' in parameter 'before' (file: /etc/puppetlabs/code/environments/deltaprep/modules/rhsm/manifests/proxy.pp, line: 16) on node cnvm01.delta.internal.ncsa.edu
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by billglick** [comment]
fixed in #5
